[package]
name = "dlib-face-recognition"
version = "0.3.2"
authors = [
    "Ashley <expenses@airmail.cc>",
    "Ho Kim <great.ho.kim@gmail.com>",
    "João Pedro Sanches Dovichi <jsanchesdovichi@gmail.com>",
]
edition = "2024"

description = "Unofficial Rust wrappers to the C++ library dlib, face recognition tools"
homepage = "https://github.com/podo-os"
repository = "https://github.com/podo-os/dlib-face-recognition"
readme = "README.md"
license = "BSD-3-Clause"

build = "build.rs"

[dependencies]
cpp = "0.5"
image = { version = "0.24", default-features = false }

[build-dependencies]
cpp_build = "0.5"

[workspace]
members = [".", "starter_template"]
